baseURL = "https://hoangchuong-web.pages.dev/"
locale = "en-us"
title = "Chuongk48"
enableRobotsTXT = true

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = false

[minify]
  disableHTML = false
