baseURL = "https://hoangchuong-web.pages.dev/"
locale = "vi"
defaultContentLanguage = "vi"
title = "Chuongk48"
enableRobotsTXT = true

[taxonomies]
  danh_muc = "danh-muc"

[markup.goldmark.renderer]
  unsafe = false

[minify]
  disableHTML = false

[pagination]
  pagerSize = 12
